### PR TITLE
feat(js): adds eslint-config-rentpath

### PR DESCRIPTION
**Pull request by Teapane**
address #17 .

### CODE REVIEW

**Comment by Teapane** [comment]
I am going to add travis to this PR as well. Lets hold off for a bit.

**Comment by Teapane** [comment]
Hey @c0 you wanna set this up under your github name `semantic-release-cli setup` or should I use mine?

**Comment by c0** [comment]
:+1: I set it up with my GH account.

**Comment by Teapane** [comment]
@c0 :boom:

**Pull request merged**
